### PR TITLE
Implement support for organization multi-branch projects

### PR DESCRIPTION
**Pull request by VanRoy**
Implementation to use remote file plugin with "Organization projects" like GitHub or Bitbucket.

### CODE REVIEW

**Comment by aytuncbeken** [comment]
Thanks for the pull request. Just one question, what localfile is used for ?

**Comment by VanRoy** [comment]
Hello,

It's used as project recognizer.

If you put 'build.gradle' in localFile field, only SCM repositories that contain build.gradle file will be created as Jenkins build.

If you set localFile to blank, all repositories are taken into account.

Do not hesitate to tell me if that not match with your plan for this plugin or if you would like that I do some improvements to my PR.

Thanks a lot.
Julien.

**Comment by aytuncbeken** [comment]
Your contribution is welcome of course. Never used project types in Jenkins, that is why I asked.

**Comment by aytuncbeken** [comment]
Thanks for the contributions

**Pull request merged**
