### PR TITLE
Match only branches containing the specified Local File

### PR DESCRIPTION
**Pull request by leonardo-filipe**
When @VanRoy implemented support for Organization Folders, a new Local File parameter was introduced. When a file is specified in this field, only repositories containing that file have a Jenkins build created.

In my use case, we have about 4000 repos, with an average of 10 branches in each. Some have nearly 100 branches. We use a Local File to configure some properties used during builds, and automatically abort builds for branches not containing it. Since most of those branches are old, and wont have this file added to them, this led to a lot of wasted storage space in the Jenkins Master, and also slowed down the search for builds.

While we are asking our developers to delete branches that are no longer used, it would be desirable to not have builds created for branches which don't contain the specified Local File. I believe there are other use cases which might benefit from this, as this is also how Custom Marker Files (a feature available only on Jenkins Cloudbees Enterprise) works.

Do not hesitate to tell me about any improvements needed on my PR, or if it doesn't match your plans.

Thanks a lot for developing this plugin, it has helped me a lot!
Leonardo

### CODE REVIEW

**Comment by leonardo-filipe** [comment]
Last build seems to have failed during checkout due to some problem with ci.jenkins.io itself. I force-pushed just an extra typo fix on README.md now, and the build succeeded.

**Comment by aytuncbeken** [comment]
Thanks for the fix.
Just wanted to learn few things about the changes you made before merging.

1. This feature is only available for Organization type jobs right ? 
2. If the user do not define any Local file, how does it continue ? My opinion is, It should continue as usual if the user do not define any local file.

**Comment by leonardo-filipe** [comment]
You're welcome.

1. No, my change makes Local File functionality available also on regular Multibranch Pipelines.
2. I agree with your opinion. If no Local File is configured, Organization Folders and Multibranch Pipelines will just continue as usual, accepting repositories and branches regardless of which files it contains.

**Comment by aytuncbeken** [comment]
I will be glad if you can make the changes to your code as we discussed on the topic number 2. Honestly, If it does not work that way, It will affect user who are using this as usual MultiBranch Pipeline like me.

**Comment by leonardo-filipe** [comment]
I'm sorry, I should have been clearer. What I meant to say, is that my change already works the way we discussed on topic number 2.

For users who leave the Local File field blank, the changes in this PR will not change how the plugin works, and all branches will continue being recognized.

**Comment by aytuncbeken** [comment]
Sorry too, I misunderstood your answer. Then everything is good to go. Thanks for the contribution!

**Comment by aytuncbeken** [comment]
I will release the new version this week and I will let you know

**Comment by aytuncbeken** [comment]
Released with version 1.7

**Pull request merged**
